// Export the template names as an enum for better maintainability when accessing them elsewhere
export enum StringTemplates {
  HIDoNotCall = 'HIDoNotCall',
  HICall = 'HICall',
  HISelectQueue = 'HISelectQueue',
  HISelectNumberToCall = 'HISelectNumberToCall',
  HIDoNotCallExplicit = 'HIDoNotCallExplicit',
  HIChangeStatusForCall = 'HIChangeStatusForCall',
  HIChangeStatusForWhatsApp = 'HIChangeStatusForWhatsApp',
  HIMakeCall = 'HIMakeCall',
  HIStartCall = 'HIStartCall',
  HIVariables = 'HIVariables',
  HIValues = 'HIValues',
  HICancel = 'HICancel',
  HISend = 'HISend',
  HIContactNotFound = 'HIContactNotFound',
  HIInteractWith = 'HIInteractWith',
  HISelectInteractionMethod = 'HISelectInteractionMethod',
  HISMS = 'HISMS',
  HIDoNotWhatsApp = 'HIDoNotWhatsApp',
  HIStartWhatsAppConversation = 'HIStartWhatsAppConversation',
  HIWhatsApp = 'HIWhatsApp',
  HIAppointment = 'HIAppointment',
  HIBostonMedicalElexial = 'HIBostonMedicalElexial',
  HIOutOf24HourWindow = 'HIOutOf24HourWindow',
  HIWhatsAppBlocked = 'HIWhatsAppBlocked',
  HIServiceLimitationWhatsApp = 'HIServiceLimitationWhatsApp',
  HIInvalidDestination = 'HIInvalidDestination',
  HIUserOptedOut = 'HIUserOptedOut',
  HIUnhandledError = 'HIUnhandledError',
  HITemplates = 'HITemplates',
  HISelectTemplate = 'HISelectTemplate',
  HIFilterTemplates = 'HIFilterTemplates',
  HIFilter = 'HIFilter',
  HIClear = 'HIClear',
  HISelect = 'HISelect',
  HILatestErrors = 'HILatestErrors',
  HINoRecentErrors = 'HINoRecentErrors',
  HIErrorFetchingTemplates = 'HIErrorFetchingTemplates',
  HIStartConversationWith = 'HIStartConversationWith',
  HISelectWhatsAppAddress = 'HISelectWhatsAppAddress',
  HIDoNotWhatsAppExplicit = 'HIDoNotWhatsAppExplicit',
  HIChangeStatusWhatsApp = 'HIChangeStatusWhatsApp',
  HIStartConversation = 'HIStartConversation',
  HINotificationAlreadyActiveConversationWithAnotherAgent = 'HINotificationAlreadyActiveConversationWithAnotherAgent',
  HINotificationAlreadyActiveConversationWithAgent = 'HINotificationAlreadyActiveConversationWithAgent',
  HINotificationAlreadyActiveConversationWithoutAgent = 'HINotificationAlreadyActiveConversationWithoutAgent'
}

export const stringHook = () => ({
  'en-US': {
    [StringTemplates.HIDoNotCall]: 'Contact marked as "Don\'t call"',
    [StringTemplates.HICall]: 'Call',
    [StringTemplates.HISelectQueue]: 'Select queue',
    [StringTemplates.HISelectNumberToCall]: 'Select number to call',
    [StringTemplates.HIDoNotCallExplicit]: 'Do not call',
    [StringTemplates.HIChangeStatusForCall]: 'To make a call, please change your status from "Offline"',
    [StringTemplates.HIChangeStatusForWhatsApp]: 'To start a WhatsApp conversation, please change your status from "Offline"',
    [StringTemplates.HIMakeCall]: 'Make a call',
    [StringTemplates.HIStartCall]: 'Start call',
    [StringTemplates.HIVariables]: 'Variables',
    [StringTemplates.HIValues]: 'Values',
    [StringTemplates.HICancel]: 'Cancel',
    [StringTemplates.HISend]: 'Send',
    [StringTemplates.HIContactNotFound]: 'Contact not found on HubSpot',
    [StringTemplates.HIInteractWith]: 'Interact with',
    [StringTemplates.HISelectInteractionMethod]: 'Select interaction method',
    [StringTemplates.HISMS]: 'SMS',
    [StringTemplates.HIDoNotWhatsApp]: 'Do not WhatsApp',
    [StringTemplates.HIStartWhatsAppConversation]: 'Start WhatsApp conversation',
    [StringTemplates.HIWhatsApp]: 'WhatsApp',
    [StringTemplates.HIAppointment]: 'Appointment',
    [StringTemplates.HIBostonMedicalElexial]: 'Boston Medical/Elexial',
    [StringTemplates.HIOutOf24HourWindow]: 'Out of 24 hour window. Start conversation using a WhatsApp template.',
    [StringTemplates.HIWhatsAppBlocked]: 'WhatsApp Business Account blocked',
    [StringTemplates.HIServiceLimitationWhatsApp]: 'Unable to send WhatsApp message due to a service limitation',
    [StringTemplates.HIInvalidDestination]: 'Invalid destination',
    [StringTemplates.HIUserOptedOut]: 'User has opted out of WhatsApp messages',
    [StringTemplates.HIUnhandledError]: 'Unhandled error',
    [StringTemplates.HITemplates]: 'Templates',
    [StringTemplates.HISelectTemplate]: 'Select a template',
    [StringTemplates.HIFilterTemplates]: 'Filter templates',
    [StringTemplates.HIFilter]: 'Filter',
    [StringTemplates.HIClear]: 'Clear',
    [StringTemplates.HISelect]: 'Select',
    [StringTemplates.HILatestErrors]: 'Latest errors',
    [StringTemplates.HINoRecentErrors]: 'No recent errors',
    [StringTemplates.HIErrorFetchingTemplates]: 'Error fetching templates',
    [StringTemplates.HIStartConversationWith]: 'Start conversation with',
    [StringTemplates.HISelectWhatsAppAddress]: 'Select WhatsApp address to start a conversation',
    [StringTemplates.HIDoNotWhatsAppExplicit]: 'Do not WhatsApp',
    [StringTemplates.HIChangeStatusWhatsApp]: 'To start a WhatsApp conversation, please change your status from "Offline"',
    [StringTemplates.HIStartConversation]: 'Start conversation',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAnotherAgent]: 'Al parecer el contacto con el que desea interactuar ya es encuentra en interacción con otro agente. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAgent]: 'Ya está interactuando con este contacto. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithoutAgent]: 'Al parecer este contacto se encuentra en una interacción activa. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}'
  },
  'es-MX': {
    [StringTemplates.HIDoNotCall]: 'Contacto marcado como "No llamar"',
    [StringTemplates.HICall]: 'Llamar a',
    [StringTemplates.HISelectQueue]: 'Seleccionar cola',
    [StringTemplates.HISelectNumberToCall]: 'Seleccionar número a llamar',
    [StringTemplates.HIDoNotCallExplicit]: 'No llamar',
    [StringTemplates.HIChangeStatusForCall]: 'Para realizar una llamada, cambie su estado distinto a "Offline"',
    [StringTemplates.HIChangeStatusForWhatsApp]: 'Para iniciar una conversación de WhatsApp, cambie su estado distinto a "Offline"',
    [StringTemplates.HIMakeCall]: 'Realizar una llamada',
    [StringTemplates.HIStartCall]: 'Iniciar llamada',
    [StringTemplates.HIVariables]: 'Variables',
    [StringTemplates.HIValues]: 'Valores',
    [StringTemplates.HICancel]: 'Cancelar',
    [StringTemplates.HISend]: 'Enviar',
    [StringTemplates.HIContactNotFound]: 'Contacto no encontrado en HubSpot',
    [StringTemplates.HIInteractWith]: 'Interactuar con',
    [StringTemplates.HISelectInteractionMethod]: 'Seleccionar método de interacción',
    [StringTemplates.HISMS]: 'SMS',
    [StringTemplates.HIDoNotWhatsApp]: 'No enviar WhatsApp',
    [StringTemplates.HIStartWhatsAppConversation]: 'Iniciar conversación de WhatsApp',
    [StringTemplates.HIWhatsApp]: 'WhatsApp',
    [StringTemplates.HIAppointment]: 'Cita',
    [StringTemplates.HIBostonMedicalElexial]: 'Boston Medical/Elexial',
    [StringTemplates.HIOutOf24HourWindow]: 'Fuera de la ventana de 24 horas. Iniciar una conversación usando un template de WhatsApp.',
    [StringTemplates.HIWhatsAppBlocked]: 'La cuenta de WhatsApp Business se encuentra bloqueada',
    [StringTemplates.HIServiceLimitationWhatsApp]: 'No podemos enviar el mensaje debido a una limitación de WhatsApp',
    [StringTemplates.HIInvalidDestination]: 'Destinatario inválido',
    [StringTemplates.HIUserOptedOut]: 'El usuario ha optado por no recibir mensajes de WhatsApp',
    [StringTemplates.HIUnhandledError]: 'Error no catalogado',
    [StringTemplates.HITemplates]: 'Plantillas',
    [StringTemplates.HISelectTemplate]: 'Seleccionar una plantilla',
    [StringTemplates.HIFilterTemplates]: 'Filtrar plantillas',
    [StringTemplates.HIFilter]: 'Filtrar',
    [StringTemplates.HIClear]: 'Limpiar',
    [StringTemplates.HISelect]: 'Seleccionar',
    [StringTemplates.HILatestErrors]: 'Últimos errores',
    [StringTemplates.HINoRecentErrors]: 'No hay errores recientes',
    [StringTemplates.HIErrorFetchingTemplates]: 'Error al obtener las plantillas',
    [StringTemplates.HIStartConversationWith]: 'Iniciar conversación con',
    [StringTemplates.HISelectWhatsAppAddress]: 'Seleccionar la dirección de WhatsApp para iniciar una conversación',
    [StringTemplates.HIDoNotWhatsAppExplicit]: 'No enviar WhatsApp',
    [StringTemplates.HIChangeStatusWhatsApp]: 'Para iniciar una conversación de WhatsApp, cambie su estado distinto a "Offline"',
    [StringTemplates.HIStartConversation]: 'Iniciar conversación',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAnotherAgent]: 'Al parecer el contacto con el que desea interactuar ya es encuentra en interacción con otro agente. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAgent]: 'Ya está interactuando con este contacto. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithoutAgent]: 'Al parecer este contacto se encuentra en una interacción activa. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}'
  },
  'es-ES': {
    [StringTemplates.HIDoNotCall]: 'Contacto marcado como "No llamar"',
    [StringTemplates.HICall]: 'Llamar a',
    [StringTemplates.HISelectQueue]: 'Seleccionar cola',
    [StringTemplates.HISelectNumberToCall]: 'Seleccionar número a llamar',
    [StringTemplates.HIDoNotCallExplicit]: 'No llamar',
    [StringTemplates.HIChangeStatusForCall]: 'Para realizar una llamada, cambie su estado distinto a "Offline"',
    [StringTemplates.HIChangeStatusForWhatsApp]: 'Para iniciar una conversación de WhatsApp, cambie su estado distinto a "Offline"',
    [StringTemplates.HIMakeCall]: 'Realizar una llamada',
    [StringTemplates.HIStartCall]: 'Iniciar llamada',
    [StringTemplates.HIVariables]: 'Variables',
    [StringTemplates.HIValues]: 'Valores',
    [StringTemplates.HICancel]: 'Cancelar',
    [StringTemplates.HISend]: 'Enviar',
    [StringTemplates.HIContactNotFound]: 'Contacto no encontrado en HubSpot',
    [StringTemplates.HIInteractWith]: 'Interactuar con',
    [StringTemplates.HISelectInteractionMethod]: 'Seleccionar método de interacción',
    [StringTemplates.HISMS]: 'SMS',
    [StringTemplates.HIDoNotWhatsApp]: 'No enviar WhatsApp',
    [StringTemplates.HIStartWhatsAppConversation]: 'Iniciar conversación de WhatsApp',
    [StringTemplates.HIWhatsApp]: 'WhatsApp',
    [StringTemplates.HIAppointment]: 'Cita',
    [StringTemplates.HIBostonMedicalElexial]: 'Boston Medical/Elexial',
    [StringTemplates.HIOutOf24HourWindow]: 'Fuera de la ventana de 24 horas. Iniciar una conversación usando un template de WhatsApp.',
    [StringTemplates.HIWhatsAppBlocked]: 'La cuenta de WhatsApp Business se encuentra bloqueada',
    [StringTemplates.HIServiceLimitationWhatsApp]: 'No podemos enviar el mensaje debido a una limitación de WhatsApp',
    [StringTemplates.HIInvalidDestination]: 'Destinatario inválido',
    [StringTemplates.HIUserOptedOut]: 'El usuario ha optado por no recibir mensajes de WhatsApp',
    [StringTemplates.HIUnhandledError]: 'Error no catalogado',
    [StringTemplates.HITemplates]: 'Plantillas',
    [StringTemplates.HISelectTemplate]: 'Seleccionar una plantilla',
    [StringTemplates.HIFilterTemplates]: 'Filtrar plantillas',
    [StringTemplates.HIFilter]: 'Filtrar',
    [StringTemplates.HIClear]: 'Limpiar',
    [StringTemplates.HISelect]: 'Seleccionar',
    [StringTemplates.HILatestErrors]: 'Últimos errores',
    [StringTemplates.HINoRecentErrors]: 'No hay errores recientes',
    [StringTemplates.HIErrorFetchingTemplates]: 'Error al obtener las plantillas',
    [StringTemplates.HIStartConversationWith]: 'Iniciar conversación con',
    [StringTemplates.HISelectWhatsAppAddress]: 'Seleccionar la dirección de WhatsApp para iniciar una conversación',
    [StringTemplates.HIDoNotWhatsAppExplicit]: 'No enviar WhatsApp',
    [StringTemplates.HIChangeStatusWhatsApp]: 'Para iniciar una conversación de WhatsApp, cambie su estado distinto a "Offline"',
    [StringTemplates.HIStartConversation]: 'Iniciar conversación',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAnotherAgent]: 'Al parecer el contacto con el que desea interactuar ya es encuentra en interacción con otro agente. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAgent]: 'Ya está interactuando con este contacto. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithoutAgent]: 'Al parecer este contacto se encuentra en una interacción activa. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}'
  },
  'pt-BR': {
    [StringTemplates.HIDoNotCall]: 'Contacto marcado como "No llamar"',
    [StringTemplates.HICall]: 'Ligar',
    [StringTemplates.HISelectQueue]: 'Selecionar fila',
    [StringTemplates.HISelectNumberToCall]: 'Selecionar número para ligar',
    [StringTemplates.HIDoNotCallExplicit]: 'Não chamar',
    [StringTemplates.HIChangeStatusForCall]: 'Para realizar uma chamada, altere seu estado diferente de \'Offline\'',
    [StringTemplates.HIChangeStatusForWhatsApp]: 'Para iniciar uma conversação de WhatsApp, altere seu estado diferente de \'Offline\'',
    [StringTemplates.HIMakeCall]: 'Realizar uma chamada',
    [StringTemplates.HIStartCall]: 'Iniciar chamada',
    [StringTemplates.HIVariables]: 'Variáveis',
    [StringTemplates.HIValues]: 'Valores',
    [StringTemplates.HICancel]: 'Cancelar',
    [StringTemplates.HISend]: 'Enviar',
    [StringTemplates.HIContactNotFound]: 'Contato não encontrado no HubSpot',
    [StringTemplates.HIInteractWith]: 'Interagir com',
    [StringTemplates.HISelectInteractionMethod]: 'Selecionar método de interação',
    [StringTemplates.HISMS]: 'SMS',
    [StringTemplates.HIDoNotWhatsApp]: 'Não enviar WhatsApp',
    [StringTemplates.HIStartWhatsAppConversation]: 'Iniciar conversação de WhatsApp',
    [StringTemplates.HIWhatsApp]: 'WhatsApp',
    [StringTemplates.HIAppointment]: 'Cita',
    [StringTemplates.HIBostonMedicalElexial]: 'Boston Medical/Elexial',
    [StringTemplates.HIOutOf24HourWindow]: 'Fora da janela de 24 horas. Iniciar uma conversação usando um template de WhatsApp.',
    [StringTemplates.HIWhatsAppBlocked]: 'Conta de WhatsApp Business bloqueada',
    [StringTemplates.HIServiceLimitationWhatsApp]: 'Não podemos enviar o mensagem de WhatsApp devido a uma limitação de serviço',
    [StringTemplates.HIInvalidDestination]: 'Destino inválido',
    [StringTemplates.HIUserOptedOut]: 'O usuário optou por não receber mensagens de WhatsApp',
    [StringTemplates.HIUnhandledError]: 'Erro não catalogado',
    [StringTemplates.HITemplates]: 'Modelos',
    [StringTemplates.HISelectTemplate]: 'Selecionar um modelo',
    [StringTemplates.HIFilterTemplates]: 'Filtrar modelos',
    [StringTemplates.HIFilter]: 'Filtrar',
    [StringTemplates.HIClear]: 'Limpiar',
    [StringTemplates.HISelect]: 'Selecionar',
    [StringTemplates.HILatestErrors]: 'Últimos erros',
    [StringTemplates.HINoRecentErrors]: 'Nenhum erro recente',
    [StringTemplates.HIErrorFetchingTemplates]: 'Erro ao buscar modelos',
    [StringTemplates.HIStartConversationWith]: 'Iniciar conversação com',
    [StringTemplates.HISelectWhatsAppAddress]: 'Selecionar o endereço de WhatsApp para iniciar uma conversação',
    [StringTemplates.HIDoNotWhatsAppExplicit]: 'Não enviar whatsapp',
    [StringTemplates.HIChangeStatusWhatsApp]: 'Para iniciar uma conversação de whatsapp, altere seu estado diferente de "Offline"',
    [StringTemplates.HIStartConversation]: 'Iniciar conversação',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAnotherAgent]: 'Al parecer el contacto con el que desea interactuar ya es encuentra en interacción con otro agente. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithAgent]: 'Ya está interactuando con este contacto. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}',
    [StringTemplates.HINotificationAlreadyActiveConversationWithoutAgent]: 'Al parecer este contacto se encuentra en una interacción activa. Si esto es un error póngase en contacto con un Administrador. ID Conversación: {{conversationSid}}'
  },
});
